# Generated by Django 5.2.3 on 2025-06-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cartorder_address_cartorder_city_cartorder_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_prod',
            field=models.BooleanField(default=True),
        ),
    ]
