"""
Django settings for safi project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

import environ
import dj_database_url

from decouple import config

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


from environs import Env
env = Env()
env.read_env()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

import os

SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = False

ALLOWED_HOSTS = [ '127.0.0.1', 'safishop-igof.onrender.com', 'www.safi-shop.com']
CSRF_TRUSTED_ORIGINS = ['https://safishop-igof.onrender.com', 'https://www.safi-shop.com']
# SECURE_CROSS_ORIGIN_OPENER_POLICY='same-origin-allow-popups'



# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',
    'cloudinary_storage',
    'django.contrib.humanize',
    # "newsletter",

    # Third Party
    'taggit',
    'crispy_bootstrap5',
    'django_ckeditor_5',
    'paypal.standard.ipn',
 #   'ajax_select',

    #custom app

    'core',
    'userauths',
    'useradmin',

    # blog
    'blog',
    # les fichiers media

    # 'whitenoise.runserver_nostatic',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'safi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'core.context_processor.default',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'safi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Environment flags used by this settings module:
# - ENVIRONNEMENT: deployment environment name (e.g. 'development' or 'production').
#   This is read from the environment and defaults to 'development' if not set.
# - POSGRES_LOCALITY: boolean override to indicate a local Postgres setup (True)
#   or a remote/production Postgres (False). Default here is True for local dev.
ENVIRONNEMENT = env.str('ENVIRONNEMENT', 'development')
POSGRES_LOCALITY = env.bool('POSGRES_LOCALITY', True)

# If running in production-like mode we switch the database to the one
# referenced by DATABASE_URL. We treat the following as production-like:
#  - ENVIRONNEMENT == 'production'
#  - POSGRES_LOCALITY == True (explicit override in some setups)
if ENVIRONNEMENT == 'production' or POSGRES_LOCALITY == True:
    DATABASES = {
        'default': dj_database_url.parse(env('DATABASE_URL'))
    }


# DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.postgresql',
#             'NAME': 'safishopdb',
#             'USER': 'safishopdbadmin',
#             'PASSWORD': '4178774Mb#',
#             'HOST': 'safishopdb.c7ieeoesox51.eu-west-1.rds.amazonaws.com',  # Or your PostgreSQL server's IP/hostname
#             'PORT': '5432',       # Default PostgreSQL port
#         }
#     }


# DATABASES = {
#         'default': dj_database_url.parse(env('DATABASE_URL'))
#     }


# AMAZON
# AWS_S3_ACCESS_KEY_ID=config('AWS_S3_ACCESS_KEY_ID')
# AWS_S3_SECRET_ACCESS_KEY=config('AWS_S3_SECRET_ACCESS_KEY')
# AWS_STORAGE_BUCKET_NAME='safi-shop'
# AWS_S3_SIGNATURE_VERSION='s3v4'
# AWS_S3_REGION_NAME='us-east-1'
# AWS_S3_FILE_OVERWRITE=False
# AWS_S3_DEFAULT_ACL=None
# AWS_S3_VERITY=True
# DEFAULT_FILE_STORAGE='storages.backends.s3boto3.S3Boto3Storage'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

MEDIA_URL = '/media/'  # or any prefix you choose

# Environment flags (ensure these are defined before use)
# Read the deployment environment (default to 'development') and whether
# Postgres is running locally (default False).

# Storage selection logic:
# - We want to use Cloudinary for media when running in production. To make this
#   robust, we enable Cloudinary when any of the following is true:
#     * DEBUG is False (explicit production mode),
#     * ENVIRONNEMENT == 'production', or
#     * POSGRES_LOCALITY is True (explicit override in some setups).
# - Otherwise, use local filesystem storage (MEDIA_ROOT) for development.
if (not DEBUG) or (ENVIRONNEMENT == 'production') or (POSGRES_LOCALITY is True):
    # Use Cloudinary for media uploads when not in DEBUG (production) or when
    # environment flags explicitly indicate production-like behavior.
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    # Ensure the Cloudinary credentials exist in environment variables or .env
else:
    # Local filesystem storage for development/debugging convenience
    MEDIA_ROOT = BASE_DIR / 'media'

CLOUDINARY_STORAGE = {
    # CLOUDINARY credentials: try in this order
    # 1) env() provided by environs (reads from .env or environment)
    # 2) os.environ fallback (in case variables are set by the system)
    # 3) None (will raise at runtime if Cloudinary is required but missing)
    'CLOUD_NAME': env.str('CLOUDINARY_CLOUD_NAME', os.environ.get('CLOUDINARY_CLOUD_NAME')),
    'API_KEY': env.str('CLOUDINARY_API_KEY', os.environ.get('CLOUDINARY_API_KEY')),
    'API_SECRET': env.str('CLOUDINARY_API_SECRET', os.environ.get('CLOUDINARY_API_SECRET'))
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CKEDITOR_5_UPLOAD_PATH = 'uploads/'

JAZZMIN_SETTINGS = {
    'site_header': "SafiShop",
    'site_brand': "On a toujours le chiox",
    'site_logo': "assets/imgs/theme/loading.gif",
    'copyright': "safibusiness@gmail.com",
}



AUTH_USER_MODEL = 'userauths.User'



customColorPalette = [
        {
            'color': 'hsl(4, 90%, 58%)',
            'label': 'Red'
        },
        {
            'color': 'hsl(340, 82%, 52%)',
            'label': 'Pink'
        },
        {
            'color': 'hsl(291, 64%, 42%)',
            'label': 'Purple'
        },
        {
            'color': 'hsl(262, 52%, 47%)',
            'label': 'Deep Purple'
        },
        {
            'color': 'hsl(231, 48%, 48%)',
            'label': 'Indigo'
        },
        {
            'color': 'hsl(207, 90%, 54%)',
            'label': 'Blue'
        },
    ]


CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': {
            'items': ['heading', '|', 'bold', 'italic', 'link',
                      'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', ],
                    }

    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': {
            'items': ['heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
                      'code','subscript', 'superscript', 'highlight', '|', 'codeBlock', 'sourceEditing', 'insertImage',
                    'bulletedList', 'numberedList', 'todoList', '|',  'blockQuote', 'imageUpload', '|',
                    'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed', 'removeFormat',
                    'insertTable',
                    ],
            'shouldNotGroupWhenFull': 'true'
        },
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                        'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side',  '|'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]

        },
        'table': {
            'contentToolbar': [ 'tableColumn', 'tableRow', 'mergeTableCells',
            'tableProperties', 'tableCellProperties' ],
            'tableProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            },
            'tableCellProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            }
        },
        'heading' : {
            'options': [
                { 'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph' },
                { 'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1' },
                { 'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2' },
                { 'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3' }
            ]
        }
    },
    'list': {
        'properties': {
            'styles': 'true',
            'startIndex': 'true',
            'reversed': 'true',
        }
    }
}


